_includes/search-form.html
_sass/_main.scss
_sass/base/_buttons.scss
styleguide/index.html

- Closes #53
- Also many other updates, as per below. The biggest thing was arranging a form field side-by-side solution that could be used throughout the site. I'm hopeful that we're there now.
- Still need to change 'mile radius' box from free-text entry to dropdown with specific options.

Polishes styles on mobile homepage form

---

_sass/_main.scss
_sass/base/_typography.scss

Addresses latest feedback on #4

Tweaks on header/footer

---

search/index.html

@shawnbot I changed the 'Edit Criteria' chevron to Font Awesome to better match Jess's comps. I am leaving this here for your review in case you had changed it to ascii intentionally.

Changes ascii to font awesome chevron to better match comps.

---

_sass/_main.scss
styleguide/school.html

Adds collapsable divs for content on individual school pages.

---

_includes/search-form.html
_sass/_main.scss
_sass/base/_buttons.scss
_sass/base/_typography.scss
_sass/base/_variables.scss
_sass/base/components/_picc-accordion.scss
index.html
styleguide/school.html

Continues to address #67 . Ready for review @shawnbot .

Mobile home edits

---

js/picc.js
js/school.js
school/index.html

Adds special designations to the school page per #44:
* Alaskan American/Native Indian/Pacific Islander
* Hispanic
* Historically Black
* Predominantly Black
* Tribal
* Women Only
* Men Only

Special designation

---

school/index.html

Adds basic padding and style to error message.

---

_sass/base/_figures.scss
school/index.html

Adds HTML/CSS MVP for graduation rate, retention and earnings sections

---

_sass/_main.scss
_sass/base/_figures.scss
_sass/base/blocks/_school.scss
school/index.html

"Academics" module on individual school page HTML/CSS MVP. Addresses a task on #145.

"Academics" module on individual school page HTML/CSS MVP

---

_sass/_main.scss
_sass/base/_figures.scss
_sass/base/blocks/_school.scss
school/index.html

"Selectivity" module for individual schools page HTML/CSS MVP. Addresses a task in #102. Pulls in web component from #134. Placeholder text for the remaining chart in this section.

"Selectivity" module for individual schools page HTML/CSS MVP

---

_data/national_stats.yaml
_data/stats.js
js/picc.js
school/index.html

This PR adds the data binding for #180. It looks like this:

Earnings stats

---

_sass/base/blocks/_school.scss
school/index.html

This addresses the HTML/CSS MVP task in #182.

"Student body" section of individual school pages HTML/CSS

---

_includes/bar_chart_template_item.html
_sass/base/blocks/_school.scss
js/picc.js
js/school.js
school/index.html

"Student body" section of individual schools pages

---

_includes/search-form.html
_sass/base/components/_components.scss
_sass/base/components/_picc-slider.scss
js/components/picc-slider.js
search/index.html
styleguide/sliders.html

Introducing the `<picc-slider>` custom element:
```html
<picc-slider max="50000" lower="10000" upper="20000">
</picc-slider>
```
This element implements the ARIA ["slider" role](http://www.w3.org/TR/wai-aria/roles#slider) (and the relevant states and properties), which should make it nice and accessible. @meiqimichelle, mind giving me a Sass/CSS code review?

Range slider

---

beta/schedule.md

Erie meyer patch 1

---

school/index.html

https://github.com/18F/college-choice/issues/292
As seen here. Definitely needs review!

Updating "students" to "undergraduate students" to close out issue 292

---

school/index.html

Updating per this issue: https://github.com/18F/college-choice/issues/294
Definitely needs review!

Fixing typo per issue 294

---

_sass/base/_base.scss
_sass/base/components/_legend.scss
search/index.html

Resolves #227. Draws a css legend.

Adds national average legend to search results

---

_sass/base/blocks/_home.scss
index.html

Removes "Not sure were to start" wizard for MVP

---

index.html

Comments out video testimonial section for MVP. This resolves #283.

Removes video from MVP

---

.travis.yml
_includes/search-form.html
js/components/multi-select.js
js/index.js
js/search.js
package.json
test/functional/search.js
test/nightwatch.js
test/pages/search.js

This PR contains a bunch of little fixes for name and state search, particularly on Firefox. I've merged in the `frontend-tests` branch here so that I can test these on Firefox. I'm watching this PR's status to see if these even run on Travis anymore.
One note for @meiqimichelle: in order for Firefox to submit the form when the <kbd>enter</kbd> key is pressed I had to [add an explicit submit input](http://stackoverflow.com/questions/2364141/enter-key-wont-submit-form-in-firefox-but-will-in-chrome-why). It appears that FF needs one of these *per fieldset*, which is really dumb. I've classed it `sr-only`, because apparently `display: none` invalidates it. :angry:

Name and state search fixes

---

_includes/search-form.html

This PR fixes the name of the region input so that it submits the right parameter to the API, and will resolve #282.

Enable region search

---

_includes/search-form.html

Updated text to "Include Online Only Schools"

---

_data/glossary.yaml
search/index.html

Jessica updated content for tooltips per Ed's feedback in 07302015 Scorecard Site Changes.docx.

Tooltip content update

---

index.html

Updated content under "Check Out These Schools" per content provided by Ed in 07172015 Data Insights.docx.

Check Out These Schools text updates

---

school/index.html

Content changes per Ed's recommendations in 07302015 Scorecard Site Changes.docx.

Content Changes

---

_includes/search-form.html
js/picc.js
js/search.js
search/index.html

Hooks up the sort order drop-down and sets its default value to descending threshold earnings, per #253.

Default sort order

---

_sass/base/blocks/_school.scss
js/picc.js
js/school.js
school/index.html

This PR will fix a couple of real data issues as I find them, tidy up and document the JavaScript in the event that somebody has to look at it next week.
I'm also switching the maps to [toner-lite](http://maps.stamen.com/toner-lite/) over SSL because the terrain styles aren't available outside the lower 48. More on that in #105 and #97.

Cleanup, bug fixes and documentation

---

_sass/base/_base.scss
_sass/base/components/_pagination.scss
js/search.js
search/index.html

This PR introduces a pagination element to the search page, per #75.

Pagination UI

---

_includes/search-form.html
_sass/base/components/_tooltip.scss
school/index.html
search/index.html

[WIP] Add tooltips to all meter and filter headers

---

_includes/header-data.html
_sass/base/blocks/_data-home.scss
_sass/base/blocks/_home.scss
data/index.html

- fixes new background splash image (should display now, and is optimized, and won't load on small sizes to improve performance)
- adds closer-to-real intro text to data tool
- revises data tool nav to latest design direction

A few fixes before demo

---

_includes/search-form.html
js/picc.js
js/search.js
school/index.html

requires change to API (now on dev)

cost per year filters hooked up to the right API

---

_data/glossary.yaml
school/index.html
search/index.html
styleguide/index.html

Average Salary -> Salary 10 Years After
Average Cost per Year -> Average Actual Cost
Fixed Glossary also

changes based on Erie’s pull requests

---

_data/stats.js
_includes/search-form.html
js/picc.js
search/index.html

changed some labels to adjust meaning, pls consider these placeholder
“Advantage Factor” is placeholder for “percentage of students
earning less than $25,000” 
adjusted sort options per #483, fixes #253

update field names per API changes

---

_includes/search-form.html
js/components/picc-slider.js
js/picc.js
js/search.js

This fixes the graduation rate slider issue in #417 and moves some of the code around for syncing up the sliders and their hidden inputs, which now gets the slider values in sync with the value in the query string if you link directly to search results.

Slider fixes

---

school/index.html

- programs offered (#538)
- acceptance rate

Comments out unlinked features

---

_sass/base/blocks/_results.scss
_sass/base/blocks/_school.scss
school/index.html

Addresses #172.
- Adds paragraph back in around cost assumptions on indiv school page.
- Adds button for calculate cost.
Passing to @shawnbot for data links.

[WIP] Adds net price calculator

---

_includes/search-form.html

Hi! I switched ZIP Code to ZIP code so that it follows AP style. For reference: http://apstylebook.blogspot.com/2009/06/state-names.html

I did a tiny copy edit on ZIP code

---

test/README.md

correct the "webdriver-manager install" command to read "webdriver-manager update" as it should.

fix "webdriver-manager update" command

---

school/index.html
search/index.html

Updating content per https://github.com/18F/college-choice/issues/651
USA!

Mailto content

---

_sass/base/components/_drawer.scss

Adds pointer to hot spot on results drawer to help UI

---

_sass/base/blocks/_home.scss
_sass/base/components/_buttons.scss
index.html

Replace paying module on home with three buttons

---

_includes/header-data.html
_includes/header.html

Add blank target to ed.gov link in the header

---

data/index.html

No more tweets, only stacks :) This addresses #264

Removes twitter from data page

---

js/picc.js

Replaces Urban with City.

---

data/index.html

Updates link to stack exchange on data page.

---

_includes/search-form.html

Change search item order

---

_config.yml

- Changes jekyll sass engine to output compressed css instead of nested.

Compress css

---

_includes/footer-data.html
_layouts/default-data.html
_sass/base/blocks/_footer.scss

Addresses #497 and #937.
Let's merge for review on dev.

Updates footer

---

_includes/search-form.html

Makes default for location dropdowns 'Any'

---

_includes/search-form.html
_sass/base/blocks/_home.scss

We didn't have as many search options as we thought we would, so we're moving advanced search back into the normal search flow...._for now_
Addresses #890

Toast advanced search (for now)

---

_includes/search-form.html

Changes none to any in special designation and religious affiliation dropdowns

---

_data/programs.csv

I ran the CSV through [csvsort](http://csvkit.readthedocs.org/en/0.4.0/scripts/csvsort.html), et voilà!

Alphabetize program listing

---

_sass/base/blocks/_results.scss
_sass/base/blocks/_school.scss
_sass/base/components/_legend.scss
school/index.html
search/index.html

Addresses #466.
In passing, this also fixes problem whereby summary meters on indiv schools pages split onto multiple lines at smaller screen sizes.

Adds legends to all meters

---

_includes/search-form.html

Replace repeated id-label pair with unique values.

---

_includes/footer-data.html
_includes/footer.html
_sass/base/blocks/_footer.scss

Adds attribution to footer.

---

school/index.html

Addresses #912. @ErieMeyer is this what you meant in that issue? If yes, merge plz! I see there is also discussion in #926 so maybe this is *not* the correct implementation and we don't actually have the words for the tooltip yet?
Looks like

Adds tooltip to earnings paragraph.

---

_includes/footer-data.html
_includes/footer.html

Addresses #996. For @ErieMeyer review.
Looks like:

Adds notices to footers.

---

_sass/base/blocks/_school.scss
school/index.html

Replace school sidebar with buttons

---

_sass/base/blocks/_data-home.scss
_sass/base/blocks/_footer.scss
_sass/base/components/_sections.scss
data/documentation.html
data/index.html

- Adjusts data home to match new MVP mock #1057 
- Adjusts data documentation to match new MVP mock #1059
- Decreases footer height #1024

Fixes data tool visual bugs

---

_sass/base/blocks/_school.scss
school/index.html

Forgot to push all changes. This is the last bullet point in PR #1097 .

One more small bug fix

---

_includes/search-form.html

Minor copy changes to HP Search Options

---

_includes/search-form.html

Reverts 18F/college-choice#1105

Revert "Minor copy changes to HP Search Options"

---

_includes/search-form.html

I got tangled up in a pull request revert. I'm moving the changes here in a new PR. Addresses #1104 .

Edits from #1105, redeux -- homepage search text edits

---

index.html

Minor changes to copy in 2 of the Fun Facts.

---

search/index.html

Minor Copy changes on Search Page

---

_includes/search-form.html

Minor copy changes

---

_data/glossary.yaml
_includes/filters.html
_sass/base/blocks/_results.scss
_sass/base/mixins/_grid-settings.scss
school/index.html
search/index.html
styleguide/index.html

Change actual cost to average annual cost

---

school/index.html

Changes wording for earnings sub-title

---

index.html

This PR merges [v1.1.2](https://github.com/18F/college-choice/releases/tag/v1.1.2), which pushes #1157 , a text change, to staging.

[staging] merge v1.1.2

---

_sass/base/blocks/_school.scss

Adds span to small screen size school heading block. Addresses #1190.

Fixes 'under investigation' on indiv school small screen sizes

---

data/documentation.html
data/index.html

Data tool HP copy changes

---

data/documentation.html

Data tool documentation page copy changes

---

_includes/footer-data.html
_includes/footer.html

Changes contact link to email address instead of general ed contact page

---

data/documentation.html

Changes data dictionary from pdf to csv

---

_config.yml
_includes/footer-data.html
_includes/footer.html

Adds site variable for app version number. Adds site version number to footers. Short-term solution for #1087.

Adds app version number to footer.

---

_sass/base/blocks/_data-home.scss
data/documentation.html
data/index.html

Addresses some tasks in #1015.

Adds links to full documentation, sample csvs and preps for dull download

---

_sass/base/blocks/_home.scss
index.html

- Adds link structure and proper styles for links in the check out these schools section.
@ErieMeyer this PR is ready for your urls when you have them. There's now a place to put them :) Plz send them my way via email or comment in #314.

[WIP] Adds links to Check Out These Schools

---

_sass/base/blocks/_home.scss

Changes splash breakpoint from small to medium. Addresses #1160 .

No splash image at until medium width

---

README.md

Updated the project summary based on text found in the IAA. Added links to college-choice-data and open-data-maker repos.

Updated project summary for launch

---

_sass/base/blocks/_home.scss
index.html

- Removes one of the check out these schools bullet points.
- Edits text in one of the other bullets.
- Makes content blocks even.

Removes one 'checkout these schools' bullet point.

---

_data/glossary.yaml

Updates race-ethnicity tooltip text.

---

school/index.html

Last-minute copy changes from @LisaGee.

Academics copy changes

---

data/index.html

Removed the word leading

---

favicon.ico

Adds symlink to favicon at root.

---

README.md

still needs final link of where to get the data, but I think it would be great to review 
and publish this changes even if the link is still TBD

detail on local setup of API with Open Data Maker

---

_config.yml
_includes/head.html
school/index.html
search/index.html

- Adds url to config for use in meta tags
- Adds twitter title attribute
Addresses #974

Fixes for og and twitter meta tags

---

README.md

changed project name to College Scorecard

---

README.md

Unless some additional preprocessing is required, the bulk download should be linked here.

Data link for README

---

.about.yml

This should resolve validation errors in the Team API

Corrects contact field on about.yml

---

.hound.yml
package.json
test/unit/api.js

An unsolicited pull request--I got excited when I saw you were adding unit tests!
* Fix the async test so that assertions actually get run (they don't as written)
* Tell Hound to use your jshint config
By the way, I noticed that your package.json uses loose pinning (e.g. "^3.5.9"). This is a little scary for a production project--probably safer to pin by minor or exact versions.

Unit tests

---

data/index.html

Updated hard-coded file size number in /data website

---

index.html

End 'Did you know ... ' with a question mark

---

_data/national_stats.yaml

This resolves #1448 by updating the national stats data file with new numbers from @claremccann.

Update national averages

---

data/documentation.html

update docs with consistent brand

College Choice -> College Scorecard

---

README.md

You can see these [here](https://github.com/18F/college-choice/tree/ci-badges/#build-status). They look like this:

add Circle CI badges

---

README.md
js/README.md

This PR updates some of the links pointing to the old repo after transitioning from 18F.

Update repo links

---

index.html

See the [release notes](https://github.com/RTICWDT/college-scorecard/releases/tag/v1.8.2) for more info.

v1.8.2 to staging (with Pell update)

---

_data/glossary.yaml

This PR is just a text update for the  grad rate tooltip.

update glossary entry for grad rate tooltip

---

_config.yml
index.html

See the [release notes](https://github.com/RTICWDT/college-scorecard/releases/tag/v1.8.3) for more info.

v1.8.3 to staging

---

_data/glossary.yaml
_data/national_stats.yaml
_sass/base/blocks/_home.scss
index.html

This PR includes some content updates for the home page as well as some updated national medians.

Content Updates for Home Page

---

_config.yml
_data/glossary.yaml
_data/national_stats.yaml
_sass/base/blocks/_home.scss
index.html

This PR includes site content updates and updates to national medians.

Site Content Updates

---

README.md

This is a small change to the readme file to get things back in line after earlier github issues.

Small Change to Resolve Earlier Github Issues

---

_config.yml

This pull request adds a sentence to the change log.

Dev to Staging

---

index.html
school/index.html

This PR updates copy where the GI Bill is mentioned to include a registered trademark symbol to resolve #1606.

GI Bill Link: Registered Trademark

---

_includes/header.html
_sass/base/blocks/_header.scss

This pull requests adds a maintenance message to the Scorecard website.

Maintenance Message

---

README.md
_includes/head.html
_includes/header.html
_sass/base/blocks/_header.scss
commit.txt
test/ci.sh
test/url.js

This PR removes the maintenance message and also updates federalist links throughout the codebase.

Revert maintenance message

---

README.md
_config.yml
data/index.html

See the [release notes](https://github.com/RTICWDT/college-scorecard/releases/tag/v1.9.4) for more info.

v1.9.4 to Staging

---

index.html

Minor update to the max Pell grant amount on the homepage.

Update max Pell grant amount

---

_data/glossary.yaml

with new tooltip text for the Academic Programs accordion.

Update glossary items

---

_config.yml
_data/glossary.yaml

See the [release notes](https://github.com/RTICWDT/college-scorecard/releases/tag/v1.9.6) for more info.

v1.9.6 to Staging

---

_data/glossary.yaml
index.html
js/src/compare.js

This PR includes some minor text changes as well as a patch for older versions of IE.

Minor updates

---

_config.yml
_data/glossary.yaml
index.html
js/src/compare.js

Please see the [release notes](https://github.com/RTICWDT/college-scorecard/releases/tag/v1.10.1) for more info.

v1.10.1 to Staging

---

index.html

Fixes text description on homepage.

Minor text change

---

data/changelog.html

Adds footnote about updated data files to change log

Add changelog footnote

---

_config.yml
data/changelog.html

Please see the [release notes](https://github.com/RTICWDT/college-scorecard/releases/tag/v1.10.4) for more info.

v1.10.4 to Staging

---

_config.yml
_data/glossary.yaml

Please see the [release notes](https://github.com/RTICWDT/college-scorecard/releases/tag/v1.10.5) for more info.

v1.10.5 to Staging

---

_includes/head.html

This updates the google meta head tag.

Add google meta

---

_layouts/default-data.html
_sass/base/blocks/_compare.scss
_sass/base/blocks/_results.scss
_sass/base/blocks/_school.scss
_sass/base/components/_buttons.scss
_sass/base/mixins/_grid-settings.scss
compare/index.html
data/archive.html
data/changelog.html
data/documentation.html
data/index.html
js/src/compare.js
js/src/data.js
js/src/picc.js
js/src/search.js
school/index.html
search/index.html
test/spec/utils.js

This PR updates the sharing functionality to include links to social networks. Additional event tracking has also been added to the search, school, and data pages.

Add social networks and ga events

---

_sass/base/_elements.scss

This PR adds css flags on print media to show background colors

Add print background flags

---

_config.yml
index.html

Please see the [release notes](https://github.com/RTICWDT/college-scorecard/releases/tag/v1.12.1) for more info.

v1.12.1 to Staging

---

data/documentation.html

This PR adds signup links for developers where they can obtain an API key for the scorecard data.

Data Documentation - API Signup Link

---

test/spec/compare.js

This PR attempts to clean up some of our selenium browser tests and avoid some async race conditions.

Optimize tests

---

compare/index.html
school/index.html
test/wdio.conf.js

This updates the school profile and comparison page to remove the writing section of the SAT.

SAT Update

---

_config.yml
compare/index.html
school/index.html
test/wdio.conf.js

Please see the [release notes](https://github.com/RTICWDT/college-scorecard/releases/tag/v1.17.1) for more info.

v1.17.1 to Staging

---

_config.yml
_data/glossary.yaml
data/changelog.html
data/index.html

This PR is part of a hotfix data update.

Change log entry update for minor data update.

---

js/src/vue/pages/search.vue

Pagination highlight was not working properly when "clearing" search form.

Alering the default page number after clear.

---

js/src/vue/mixins/LocationCheck.js

- Adding failure callback and timeout option.
- minor clean up.

Cleaning up location check and adding timeout

---

js/src/components/vue/NetPriceLink.vue
js/src/components/vue/SearchResultCard.vue
js/src/components/vue/Share.vue
js/src/vue/mixins/ComplexFields.js

This PR includes: 
* UI improvements to the search results cards to improve access to school profile pages. 
* Fix for the share via email link
* Fix for the transition page truncating URLs that include multiple get parameters

Minor Updates 

---

js/src/components/vue/SearchForm.vue
js/src/components/vue/SearchResultCard.vue
js/src/vue/pages/search.vue

Added a reset to pagination when filters are adjusted.

Bugfix reset pagniation

---

.circleci/config.yml
Gemfile.lock
js/src/app.js
js/src/components/vue/Share.vue
js/src/vue/pages/compare.vue
js/src/vue/pages/school.vue
js/src/vue/pages/school_fields.vue
js/src/vue/pages/search.vue
package-lock.json
package.json

- Added share URL feature, clicking share URL will copy current URL to clipboard
- Altered the share component to hide certain "Share" items
- Updated compare page to update URL when items are passed via local storage.
- Added small delay to CircleCI deployment to ensure that browser tests pass. Delay of 30 seconds between when Ferderalist finishes building and when the browser tests begin.

Feature - Share URL

---

.jshintrc
js/src/vue/pages/compare.vue
package-lock.json
package.json
webpack.prod.vue.config.js

- Fixed compare back button: Back button will default to '/search' when not explicitly set.
- Improved removal of comments during production build
- Updated jshint config to quell hound warnings.

Bugfix 20191219

---

js/src/components/vue/compare/Row.vue

This PR updates the institution name to be a link back to the school profile from the compare page.

Feature: Compare Page Links

---

js/src/vue/pages/data_changelog.vue

Adding proper change log entry for previous version.

Adding updated changelog

---

js/src/vue/pages/data_changelog.vue

Reverts RTICWDT/college-scorecard#1761
Reverting changes based on feedback for now.  Change log does not need to reflect minor feature updates.  Those items can be handled with Git log status.

Revert "Adding updated changelog"

---

_config.yml
_includes/js-config.html
_plugins/environment_variables.rb
data/documentation.html
js/src/vue/pages/data_documentation.vue
package-lock.json
package.json

- Added Embedded API key signup form
- Added a recaptcha workflow to deter bot traffic.

Feature api key signup

---

js/src/vue/pages/data_documentation.vue

Small fix to add a compact version of the ReCaptcha form.

Adding a compact recaptcha on mobile

---

__tests__/utility/url.js
js/src/vue/pages/school.vue
test/url.js

Updated FOS undergraduate count to better reflect undergraduate FOS on School Profile Page.

Update FOS Undergraduate Count

---

_config.yml
_plugins/environment_variables.rb
js/src/vue/pages/school.vue
school/index.html

Adding Mapping change to annual update branch.

Dev school map google

---

__tests__/e2e/PageSearch_test.js
_config.yml
js/src/vue/pages/data.vue
js/src/vue/pages/data_changelog.vue
js/src/vue/pages/data_documentation.vue
package-lock.json
package.json

- Various updates in preparation for the annual data refresh release.
- Updated Vuetify to fix polyfill issue on IE and Safari with `v-img`

2020 annual update

---

README.md

Updating readme with new configuration workflows

---

js/src/vue/pages/school.vue

- Fixing issue container sizing issue for static map on iOS 13 Safari.  Map container would enlarge when increasing font size.
- Altered the max of map.  Most noticeable on tablets or larger mobile displays.

Bug map with zoom

---

package-lock.json
package.json

Dev dependency updates

---

__tests__/e2e/PageIndex_test.js
js/src/components/vue/NameAutocomplete.vue
js/src/components/vue/SearchForm.vue
js/src/vue/api.js
js/src/vue/constants.js
js/src/vue/mixins/PrepareParams.js
js/src/vue/pages/index.vue

Updated the `NameAutocomplete` Vue component to use a new `school.search` field.  The new field allows for searching of institution names and aliases.

Feature: Name Search + Alias

---

_config.yml
data/documentation.html
js/src/vue/pages/data_documentation.vue

Removing ReCaptcha v2 workflow from `/data/documentation` page due to issues rendering in IE 11.  Some versions of IE 11 were not able to successfully render the page.  Issue is tied to the ReCaptcha functionality specifically.  Removing the ReCaptcha workflow to ensure page will render for all IE 11 users.  ReCaptcha will be added in a follow up patch after an upcoming release.

Hotfix: Removing recaptcha workflow from API Signup Form

---

js/src/vue/pages/data.vue
js/src/vue/pages/data_changelog.vue

Adding updated Dates

---

_config.yml
data/documentation.html
js/src/vue/pages/data_documentation.vue

Fixed issue with IE 11 and ReCaptcha on `data/documentation/`

Bugfix test recaptcha ie11

---

_config.yml

- Small update to `rack`
- Incrementing version number for release.

Updating dependencies

---

Gemfile.lock
_config.yml
package-lock.json
package.json

Minor version updates to resolve potential security problems.

Updating site dependencies

---

_config.yml
js/src/vue/pages/data.vue
js/src/vue/pages/data_changelog.vue
sitemap.xml

- Updated site dependencies to address potential security issues.
- Updated data file download links to point to new host at: [data.ed.gov](https://data.ed.gov/)

Open Data Platform Data Files and Minor Dependecy Updates
