_sass/base/_base.scss
_sass/base/_loadable.scss
_sass/base/_variables.scss
_sass/base/mixins/_loadable-state-display.scss
js/search.js
search/index.html
styleguide/index.html

This PR introduces some utility classes for specifying the visibility of various elements in the scope of "loadable" elements. For instance:
```html
<div class="loadable">
<p class="show-error error-message">This is an error message, hidden by default.</p>
<p class="show-loading">Loading...</p>
<p class="show-loaded">Loaded!</p>
</div>
```
The `show-{state}` and `hide-{state}` classes are "activated" by toggling corresponding classes on the `loadable` parent in JavaScript, using the `js-{state}` classes:
```js
var loadable = d3.select('.loadable')
.classed('js-loading', true);
d3.json('data.json', function(error, data) {
loadable.classed('js-loading', false);
if (error) {
return loadable.classed('js-error', true)
.select('.error-message')
.text(error);
}
loadable.classed('js-loaded', …
```

[WIP] Load states

---

_config.yml
_includes/head.html
_includes/search-form.html
_layouts/default.html
styleguide/index.html
styleguide/results.html

In some cases, the Liquid templates followed the `baseurl` tag with a `/`, while in others they did not. This inconsistency became a problem when overriding the `baseurl`, leading to either double slashes or missing slashes, depending on the use.
This PR standardizes to the convention of omitting the trailing slash from the `baseurl`. Without a `baseurl`, all links are relative to the root.

Omit trailing slash from basurl for consistency

---

_includes/search-form.html
_sass/_main.scss
_sass/base/_buttons.scss
_sass/base/_typography.scss
_sass/base/components/_picc-accordion.scss
_sass/base/extends/_buttons.scss
index.html

Re: #67 
1. Adjusted header to shrink at mobile sizes.
1. Added line break to ensure wizard button text always breaks in the place we want it to.
1. Shrunk collapsed accordion area to ~52px.
1. Set primary button height to 55px.
1. Set wizard button height to 76px.
1. Set space between Noun Project icon to 14px.
1. Set width of secondary buttons to 280px.
1. Set font size on secondary buttons to 12px.
1. Changes footer to bold.
1. Adds placeholder text to name field.
1. Removes student-to-faculty ratio search option.
1. Changes placeholder text on free enter search for major to 'Type a major'. I thought 'Specify a major' was too academic....but open to suggestion.

Mobile home design audit edits

---

_sass/_main.scss
_sass/base/_base.scss
_sass/base/extends/_centered.scss
index.html
school/index.html

This PR introduces a general-purpose `centered` class and "applies" it (with `@extend`) to a bunch of the home page sections, which obviates the need for "undoing" the centered alignment with `text-align: left` elsewhere.
There are also some other random tweaks in here, including:
1. turning the key facts bits into a template loop so that they're easier to tweak
2. using `<b>` instead of `<span>` tags for the big, important key facts snippets
3. fixing an HTML comment error introduced by commented elements in the search form

Make centered things explicit

---

_plugins/environment_variables.rb
js/api.js

This PR adds a modified version of [this Jekyll plugin](https://gist.github.com/nicolashery/5756478) that adds the `API_BASE_URL` and `API_KEY` environment variables to Jekyll's `site.config`, which makes them available as template variables `site.api.baseurl` and `site.api.key`, respectively.

Import environment variables into template context

---

_data/national_stats.yaml
_data/stats.js
js/components/picc-meter.js
js/picc.js
js/school.js
school/index.html

This PR will get the placeholder values caught up with the data for the elements that exist on the page, including:
* "Costs" section:
- "Financial Aid & Debt" section:

[WIP] More school page data

---

_includes/search-form.html
_sass/_main.scss
_sass/base/_base.scss
_sass/base/blocks/_results.scss
_sass/base/mixins/_grid-settings.scss
search/index.html

This addresses the HTML/CSS MVP task in #190 .
- Adds meters to search results for a quick snapshot of school stats.
- Makes three-up layout for results
- Adds basic responsive work
- Adds 'edit search criteria' MVP
- Hides filters/criteria in mobile until we decide what to do with them.

Refines search results page.

---

_sass/base/_variables.scss
_sass/base/blocks/_results.scss
_sass/base/blocks/_school.scss
_sass/base/components/_picc-meter.scss
js/components/picc-meter.js
js/picc.js
js/school.js
js/search.js
search/index.html

This PR moves all of the templating directives (the bits of logic that prep API data for display in the document) for schools into the common `picc.js` script so they can be used by both the search results and institution pages (and potentially other pages in the future). With all of the directives in place on the search results page, we can now see results like this:
It also fixes #142, a new bug with the meters being rendered in search results, and adds text for the 2-/4-year designations of primarily Certificate and Graduate degree-granting institutions, which relates to #81.

Common directives

---

js/picc.js
school/index.html

This PR fixes the special designations on the school page so they're read from the data. The HTML does what it's supposed to, but the CSS has its quirks with long values.
All you, @meiqimichelle!

Fix special designations

---

_includes/header-data.html
_layouts/default-data.html
_sass/base/_base.scss
_sass/base/_variables.scss
_sass/base/blocks/_data-home.scss
_sass/base/blocks/_header.scss
data/index.html

This PR stubs out the data tool homepage and also adds desktop implementations for the title bar/nav and the first section of the page (intro). This addresses #263 and #143.
It also gets at #264 out of priority order, but it was easy to add that one in while I was in that section of the page.

Stubs out data home

---

js/school.js
school/index.html

There was an issue with the "Selectivity" section not having an id, which, combined with the logic for expanding sections by id in the hash made that section expand by default. This fixes both problems.

Fixes school accordions

---

_includes/search-form.html

This resolves #281.
- Changes title of section to Area of Study
- Removes one of the input areas
- Changes next on remaining select input to better reflect title text change
@shawnbot I left the second input in the HTML, commented out, because I wasn't sure if you wanted to do a type-ahead here or a drop-down. The content (text) have been updated in both so whichever you use to hook up the data you're good to go.

Updates to 'degree' section of search

---

_config.yml
_data/states.csv
_includes/search-form.html
_sass/base/_base.scss
_sass/base/_utility.scss
_sass/base/components/_buttons.scss
_sass/base/components/_combo-box.scss
_sass/base/components/_forms.scss
_sass/base/components/_multi-select.scss
index.html
js/components/aria-accordion.js
js/components/combo-box.js
js/components/multi-select.js
js/index.js
js/picc.js
js/search.js
search/index.html

This PR resolves #37 by implementing @jjoteal's design for the multi-state search. Here's how it works:
There's a new `<multi-select>` element that manages one or more `<select>` elements within it, and exposes an *input-like* API of its own: it has `name`, `type`, and `value` properties, and dispatches `change` events whenever its value changes. This means that the library we're using to get and set form data ([formdb]) treats it just like any other form element.
The `<multi-select>` element treats its initial contents as a "template" that's repeated when its value is set (either as an array or when parsed as one via comma-separated strings). So you can set the state element's value to `'CA'` and it'll show one drop-down with that value selected:
When you click on the "ADD" button (it …

Multi-state search

---

_layouts/default-data.html
_layouts/default.html
js/picc-analytics.js
js/picc-dap.js

This PR adds code snippets for 18F-PICC google analytics as well as the cross-Federal Digital Analytics Program. There are other tasks necessary to get all team members access to said analytics, but first things first.
@shawnbot I can't think of any reason not to merge these now -- I don't mind our initial dev work getting tracked once it is pushed. What do you think? Is it best practice to wait? I feel like we should test it anyways before we need it.

Adds 18F-PICC and DAP analytics to consumer tool and data tool

---

_layouts/default.html
js/picc.js

This adds support for branch-specific API configurations in Federalist. This means that we can use a custom config that looks like:
```yaml
API:
baseurl: https://api.data/gov/secret-api/beta/
dev:
baseurl: https://api.data.gov/secret-api/dev/
staging:
baseurl: https://api.data.gov/secret-api/staging/
master:
baseurl: https://api.data.gov/secret-api/production/
```
If you're using a `_config.local.yml` for local testing, you shouldn't need to change anything because the `site.branch` Liquid variable will be unset, and it should use whatever you've specified in your local config's `API` variable. You can confirm that this is the case by looking at the rendered HTML source of any page and checking the `data-env` attribute of the `<body>` element, which should be blank locally. As a bonus, we …

Add support for branch-specific API URLs in Federalist

---

_plugins/environment_variables.rb

note: plugins are ignored by Federalist

fix CloudFoundry deploy script

---

_includes/search-form.html
js/components/picc-slider.js
js/picc.js
js/search.js
search/index.html

... and fix field names.
We are now sorting by:  2011.earnings.threshold_earnings_percent:desc
Salary After Graduation is: 2011.earnings.6_yrs_after_entry.mean_earnings.lowest_tercile
Montly student loan payment: 2013.debt.median_debt_suppressed.completers.monthly_payments
Cost is incorrect filtering only private schools:  2013.cost.avg_net_price.private
Comletion rate is also incorrect, tied to only 4 year schools: 2013.completion.rate.four_year
Note: requires https://github.com/18F/open-data-maker/pull/118 to be deployed on the API server.

Enable slider fields

---

_config.yml

Addresses #432.
Does not change `baseurl` so as not to interrupt development. We can change this later as needed.

Updates site title.

---

js/school.js

Used to say “School / Whatever University”
now just has the school name
addresses #478 (at least partially)

school name in browser title

---

_includes/search-form.html
js/picc.js
js/search.js
search/index.html

This PR updates the search form to use more human-friendly names for fields and their respective values so that the search URLs don't include API-specific field names or values. This means that the search result URLs are cleaner and more resilient to future API changes, such as with field names. For instance, before these changes the default search URL would expand to something like this if you searched for schools with "art" in their name:
```
/search/?name=art&degree=2..3&sort=2011.earnings.6_yrs_after_entry.percent_greater_than_25000%3Adesc
```
Now it expands to just:
```
/search/?name=art&sort=advantage:desc
```
Along the way I also fixed some slider-related bugs and ensure that they all work as expected, with the notable exception of monthly loan payment, the data for which is …

Normalize search URLs

---

js/picc.js
js/search.js

This resolves #449 by adding `2013.student.operating=1` to the API request parameters for every search.

Only load open schools

---

_sass/base/_typography.scss
_sass/base/blocks/_results.scss
school/index.html
search/index.html

This PR makes results cards all the same height, as per #335. This solution only works with school names that stay on three lines, but we decided this would cover the vast majority of schools.
This also includes outstanding spacing and typography bugs on the cards.

Make results cards all the same height

---

_sass/base/_typography.scss
_sass/base/blocks/_results.scss
_sass/base/blocks/_school.scss
js/picc.js
js/search.js
school/index.html
search/index.html

Addresses #201 
Adds share button that has the beginnings of a `mailto` to the results page and the individual school pages.
Also adds a thin border around the map as with the toner tiles its sometimes hard to see where the map is, especially now that the share button is right above it.
@shawnbot I believe the only thing left is to insert the current url into the mailto, but would appreciate another eye on that mailto generally.

Adds share `mailto` to results and individual school pages

---

_sass/base/components/_aria-accordion.scss

This PR removes `overflow: hidden` from the `<aria-accordion>` styles, which resolves the tooltip overlap issues described in #463.

Fix tooltip overflow inside <aria-accordion> elements

---

js/picc.js

This addresses the display of the federal loan rate, which is now a single number in the API.

Fix loan rate per #573

---

test/README.md

I added instructions on how to install java with brew cask. When I installed Java in the traditional "installer from Oracle" way it didn't work for webdriver-manager.

added instructions on how to install java

---

js/picc.js
js/search.js
school/index.html

This will resolve #201.
@meiqimichelle the problem with the link was that one of my URL-encoded line breaks (`%3A`) was missing its `A`, so the browser failed to parse it. I added a safeguard to also encode the URL itself, just in case other browsers are more strict about this type of thing.

Fix school share link

---

js/picc.js

This appears to have changed from `school.DISTANCEONLY` to `school.online_only`, but the change was simple.

Use the right field for online only

---

_includes/search-form.html

This resolves #473 by re-introducing the overall national averages for net price, graduation rate and median salary to the corresponding filter sliders on the search page:

Re-add national averages for sliders

---

_sass/base/_variables.scss
_sass/base/components/_legend.scss
_sass/base/components/_picc-meter.scss

Changes the width of the meter average line and the national average line to be the same at 2 px instead of 3 and 1, previously. Addresses #556.

Meter line width

---

_sass/base/blocks/_school.scss
js/picc.js
school/index.html

This addresses #423:
- Replaces the meter with a large % number and a sentence describing the relationship of the >$25k earners to the population of high school graduates.
- Updates the "Salary 10 Years After" title of the lower meter to read "Average Salary 10 Years After".
@meiqimichelle I could use some eyes on the classes I used for layout and the CSS tweaks I made. They might need some jiggling.

[WIP] Rejigger earnings display

---

_sass/base/blocks/_school.scss
js/school.js

Stamen's tiles (and the underlying OSM data) are licensed under [Creative Commons Attribution](http://creativecommons.org/licenses/by/3.0/), which means that they have to include attribution. I've styled the attribution minimally:

Add map tile attribution

---

js/picc.js

This PR updates the part-time share calculation to use the `2013.student.PPTG_EF` field per #537. I've also added a task to #584 to update it again when we transition to the v1 API.

Fix part-time share numbers

---

_sass/base/components/_picc-meter.scss
js/components/picc-meter.js
js/picc.js

This PR introduces a "no data" state to the `<picc-meter>` component, which looks like this in the search results:
and like this on the school pages:
There are some weird issues with `0` values (as opposed to `null`), but I think this gets us most of the way there. It seems like for most of the meters, anyway, that `0` should be interpreted as `null`.

Add meter "No data available" state

---

js/picc.js

This PR changes the behavior of the zip code input on the search page so that:
1. If a zip code is supplied with a distance, the query string parameter is named `zip`, because I think this is hard-coded in the API (can you confirm, @ultrasaurus?). ([test url][test distance])
2. If a zip code is suppled *without* a distance, the query string parameter is named `school.zip` so it matches the specific field. ([test url][test zip])
[test distance]: https://federalist.18f.gov/preview/18F/college-choice/fix-distance-search/search/?zip=10002&distance=20
[test zip]: https://federalist.18f.gov/preview/18F/college-choice/fix-distance-search/search/?zip=10002

Tweak zip code search parameters

---

_sass/base/_utility.scss
_sass/base/components/_picc-range.scss
js/components/picc-range.js
js/picc.js
school/index.html

This addresses a couple of issues related to the SAT and ACT charts:
* Removes midpoint (median) scores per #102 (via #382)
* Min/max label overlaps: #666 
* Style adjustments per #344 (sans the average scores, which are no longer visible)
* Adds basic "no data" display for SAT & ACT scores per #528

Test score chart tweaks

---

_sass/base/blocks/_school.scss
js/picc.js
school/index.html

This addresses #465, and it looks like this:
@meiqimichelle I got a little lazy naming some of the classes for the "of students" bits that sit within a `<span class="fact_number">`, but I don't think my choices were egregiously bad. Let me know if you disagree. :trollface:

Add Pell grant percentage

---

js/school.js

The marker pop up on the map for the school wasn't grabbing the school name from the right place.

Fix school name in map popup

---

_data/national_stats.yaml

The overall `repayment_rate` key in `national_stats.yaml` had an errant `_4` suffix on it. This will address #753.

Fix repayment rate national average

---

school/index.html

Suggest changing "Calculate your exact net price" to "calculate your personal net price."  A college's net price calculator can't give an individual his/her exact net price, but it can give a personal estimate.

Copy change: "Calculate your personal net price"

---

_config.yml
_sass/base/components/_tooltip.scss
js/compat/custom-event.js
js/components/aria-accordion.js
js/components/picc-slider.js
js/picc.js
js/search.js
search/index.html

This PR will address #901, #851, #900 (#844), and #894.
Thankfully, most of the problems boiled down to a flaw in the [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) polyfill that I included in `aria-accordion.js`. So most of the work here involves moving that out into a separate script, `compat/custom-event.js`, which uses IE's proprietary `document.createCustomEvent()` if available. With custom events working, accordions open and close and charts update without issue.
:warning: The fix for #901 involved adding a flag that disables search form resubmission when the drawer is toggled. It doesn't work 100% of the time, but the flag is only set to `false` when the drawer toggle changes, then it's set back to `true` for the next change. This seems solid to me, but …

IE11 and interaction fixes

---

_sass/base/blocks/_results.scss
_sass/base/components/_under-investigation.scss
js/picc.js

- Fixes missing 'under investigation label' that got accidentally removed with some API naming changes.
- Polishes 'under investigation' UI to account for new card widths
- Makes cards move from 4-up to 3-up and then 2-up per row sooner so we don't have super-skinny cards on the 4-up view. This also helps with the 'under investigation' display.
This addresses #943

Under investigation

---

_sass/base/_typography.scss
_sass/base/blocks/_school.scss

Changes background of special designations to light blue as per #723 . Fixes incorrect heading sizes in passing as per #941.

Changes background of special designations to light blue

---

_layouts/default-data.html
_layouts/default.html
_sass/base/_base.scss
_sass/base/_utility.scss
_sass/base/components/_browser-compat.scss

Per #455. It looks like this, and shows up in IE≤9:

Add browser compatibilty message

---

_includes/head.html

We now have OpenGraph metadata, which will tell crawlers what this site's title, description and "type" are. This addresses #132.
@meiqimichelle I guess the meta description is redundant?

Add OpenGraph metadata

---

_includes/search-form.html

This addresses the final requirement in #490 by checking the "Include Online Only Schools" box by default.
**Please note:**
1. This results in an additional parameter added to the URL query string (`&online=1`) by default.
1. Old search URLs that do not include this flag *will now be rewritten to include it*, which will change search result totals.
Mostly this is for @LisaGee and @hollyallen, who I'm pretty sure are expecting certain counts to match.

Check the "include online only schools" box by default

---

_includes/search-form.html
_sass/base/blocks/_home.scss
_sass/base/blocks/_results.scss
_sass/base/blocks/_school.scss
index.html
school/index.html
search/index.html

@jjoteal These are the high-priority visual bug fixes from our list, minus the data tool. I'll do the data ones in a separate PR so we can start reviewing these live on `dev`
- Closes all search fields on home by default #1051
- Makes homepage background image scroll with the rest of the site #1022
- Makes indiv school title sizes smaller #1039 
- Reduces padding around form submit button #1021
- Adjusts positioning of arrow in the higher/lower than average displays, and adjusts styles on the words #433 
- Removes circle around socio-econ and adjusts full/part-time student display. #925 and #425
- Changes color and size of h2 in indiv school headings #1032 
- Confirms text treatment on results cards. Changes 'undergraduate students' to 'undergraduates' so the text doesn't have to be tiny …

High-priority visual bug fixes

---

_includes/bar_chart_template_item.html
_includes/search-form.html
_sass/base/_variables.scss
_sass/base/blocks/_footer.scss
_sass/base/blocks/_home.scss
_sass/base/blocks/_results.scss
_sass/base/blocks/_school.scss
_sass/base/components/_buttons.scss
school/index.html

This PR addresses medium priority visual bugs
- Makes full-part time stats smaller on mobile so they are less ugly. #1047 
- Gets closer to proper ethnicity chart look/feel #1034
- Adds tooltip to socio-econ header #924 
- Improves spacing of Get The Best Deal buttons on homepage at small sizes #1029 
- Reduces size of attribution in footer, and ensures that it stays on two lines at all but the teeniest screen sizes. #1088
- Matches remove state button to mock #1031 
- Gives mobile-size cards a bit of an edge so they still look like 'cards' #342

Medium priority visual bugs

---

_sass/base/blocks/_home.scss
_sass/base/blocks/_school.scss
_sass/base/components/_pagination.scss
index.html

This PR addresses lower priority visual design bugs
- Adds left-right padding to Start My Application button so it is not squished at small screen sizes (I accidentally merged this straight to `dev`, but still want to record as part of this set of bugs for review)  #1043
- Reduces padding on top of pagination at small screen sizes and moves to left. #1038
- Aligns top of indiv schools heading with map #1035
- Adds perma-scrollbar to academics list, and also makes the size of that section respond to the size of the table. #635 
- Makes costs table headings uppercase #296
- Fixes By The Numbers text flow on small screen sizes #1053 
- Adds 20px of space next to Check Out These Schools #1023

Lower priority visual design bug fixes

---

_sass/base/blocks/_footer.scss
_sass/base/blocks/_school.scss

From @jjoteal feedback on yesterday's visual bug work
- Make table headings bold as well as uppercase for #296 
- Reduce footer bottom margin a tad more (after we made the attribution smaller, I forgot to make the foot height smaller, too) #1024 
- Adds heading to 'earning potential' stat and adds tooltip #1033

A few minor visual bug edits

---

data/documentation.html

latest API is at /v1/schools
I know it is not correct grammar but i think
the period at the end of the URL was confusing
(top right of page)
Also adjusted ‘location’ category, since
we won’t be able to fix that for v1 API

Data documentation: corrections in URL format & fields

---

school/index.html

This is a WIP fix for #1196 that:
1. Changes the "Students Receiving Federal Aid" figure title to "Students Receiving Federal Loans".

Financial Aid section updates

---

_sass/base/blocks/_results.scss
_sass/base/components/_pagination.scss
search/index.html

Reduces pagination at small widths, and also display-nones lables instead of visibility hidden. Addresses #1071.

Fixes screen width bug

---

_sass/base/_variables.scss
_sass/base/blocks/_results.scss
_sass/base/components/_gallery.scss
_sass/base/components/_search-toggles.scss
_sass/base/components/_tooltip.scss
search/index.html

Adds variables for z-index so they're easier to keep track of. Removes stray tooltip-target that was messing up things for the under investigation label tooltip. Addresses #971 .

Fixes under investigation tooltip issue

---

_sass/base/blocks/_school.scss
school/index.html

Fixes misplaced div and selector for spacing beneath paragraphs

---

_includes/head.html

Makes meta links to images full url instead of relative. It will show the background image on the homepage.
Addresses #1279.

Fixes missing images in share tags

---

_data/states.csv

This runs the states through [csvsort](http://csvkit.readthedocs.org/en/0.4.0/scripts/csvsort.html) to ensure that they're sorted by name.

Order states by name

---

_config.yml

Corrects API listed in config to point to the live API vs the TEST one. This
is done to speed up onboarding of new contributors.
https://github.com/18F/college-choice/issues/1315

Update config api

---

.about.yml

`milestones:` takes a list of strings; any string with a colon in it must be quoted, or the YAML parser interprets the string as a key/value pair.
cc: @hollyallen

Fix dlapiduz's GitHub ID; quotes around milestones

---

_sass/base/blocks/_school.scss

Not enough padding causes large student body numbers to be squished.
Before
------------
After
--------

Increase padding on student population number

---

test/a11y.js
test/ci.sh

This PR fixes a couple of issues with the CI test suite:
1. The a11y test runner was assuming that it would get results back, so it would fail if it didn't (which is what happens when there are no warnings or errors).
1. The `test/ci.sh` script now runs with bash, properly sets the `branch` variable for comparison, uses `==` for equality tests, and _might_ even resolve #1423.

CI test fixes

---

README.md
js/README.md

This addresses #1004 and adds specific documentation for how we manage dependencies, build the browser bundle, and handle merge conflicts. You can see the changes to the project README [here](https://github.com/18F/college-choice/tree/js-docs#javascript), which now just link to the [new JS docs](https://github.com/18F/college-choice/tree/js-docs/js#readme).

Improved JavaScript docs

---

_sass/base/blocks/_school.scss

Fixes #1419.
I mucked around with the CSS a little more than I'd like. On my Macbook Air, the previous CSS eliminated the left/right padding, which didn't look good. The downside to adding the padding back is that on medium screensizes the text within the button breaks onto two lines easily.
I'd like some feedback on whether or not this padding change is necessary. Here's how it looks right now on my Macbook Air, browser full-paged:

Increase contrast for the school page sidebar.

---

circle.yml
package.json
test/a11y.js
test/server.sh
test/spec/schoolpage.js

This addresses #1471 by reorganizing the CI test runner. Previously, the `test/ci.sh` script did all of these things in serial:
1. Figure out which API base URL to use based on `$CIRCLE_BRANCH`.
1. Build the site with `jekyll build`.
1. Serve it with the Node-based `http-server` (which was _slightly_ faster than Jekyll) in the background (with `&`).
1. Wait for the server to start up with `wget --waitretry=1`.
1. Run the browser tests, and kill the server then `exit 1` if they fail.
1. Run the a11y tests, and kill the server then `exit 1` if they fail.
This was super brittle and difficult to debug, so I refactored it into four steps that run as separate commands in the `circle.yml`:
1. The API base URL detection and server startup happen in `test/server.sh`, build and serve with Jekyll, …

Fix CI false positive

---

_includes/head.html

This should wrap up #1291 by adding a plain old `description` meta tag in addition to the `og:description`.

Add meta description

---

.hound.yml
.jshintignore

This adds a `.jshintignore` file that ignores `js/picc.js` (which is minified and essentially un-lintable) and tells @houndci to use it.

Tell Hound CI to ignore minified JS

---

circle.yml

This is a possible fix for #1502 that upgrades to PhantomJS 2.0, which _might_ work around the 1.x release's TLS issues and allow it to load the production URL. (Tip o' the hat to @konklone for [that suggestion](https://github.com/18F/college-choice/issues/1502#issuecomment-190554993)).
We actually won't know if this works until we merge to master, but the tests ran successfully on this branch so I'm going to merge up and tag a new patch release before we release to staging.

Use PhantomJS 2.0 on Circle CI

---

_config.yml
data/index.html

[:sunglasses: preview on Federalist](https://federalist.18f.gov/preview/18F/college-choice/data-docs-update/data/)
This resolves #1510 by listing the date on which the data was last updated (March 2, 2016). I've also cleaned up the HTML and uppercased the acronym "CSV" in the download links.

Data docs update

---

_config.yml
data/index.html

This PR updates the data download URLs to point at the new S3 bucket and remove the parentheses from CSV filenames.

Update data download URLs

---

data/index.html

[:sunglasses: preview on Federalist](https://federalist.18f.gov/preview/18F/college-choice/download-baseurl/data/)
This switches the data download base URL from:
```
https://download.collegescorecard.ed.gov
```
to:
```
https://collegescorecard.ed.gov/downloads
```

Update data download base URL

---

_config.yml
_includes/search-form.html
search/index.html

[:sunglasses: preview on Federalist](https://federalist.18f.gov/preview/18F/college-choice/fix-keyboard-submit/)
This is a fix for #1518.
Previously, pressing <kbd>enter</kbd> in the search forms triggered a form submission, but I broke this in the process of bringing better keyboard accessibility to our accordions in #54. The fix was to add `type="button"` to all of our accordion button elements, which prevents browsers from treating them as submit buttons and short-circuiting the form submission. [MDN has the skinny](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type).

Fix keyboard enter press on search forms

---

data/documentation.html

This is a small update to include a trailing slash on an API url on the data documentation page. It can be merged into the next set of site updates.

Data Documentation Update

---

README.md
data/index.html

As part of the migration to GovCloud, this PR points the download bucket to the new GovCloud instance.

Update downloads bucket url

---

_data/states.csv

This is in addition to the "region" location select menu (Outlying Areas).

Add outlying territories to state location select menu

---

Gemfile.lock

This updates Rack to v1.6.11 to patch `CVE-2018-16471`.

Update Build Dependencies

---

.circleci/config.yml
compare/index.html
school/index.html
test/spec/compare.js
test/spec/schoolpage.js
test/spec/search.js
test/wdio.conf.js

This PR includes a couple minor fixes.
- The comparison page was missing the predominant degree breakouts / groupings for 4yr, 2yr, and certificate schools in the Financial Aid & Debt accordion.
- The link to the FAFSA application needed to be updated in the  Financial Aid & Debt accordion on the school page.
Also, some browser tests needed some tweaks.

Minor fixes

---

js/src/vue/mixins/ComplexFields.js
js/src/vue/pages/school_fields.vue

This fixes an issue that appeared on the search results when an institution did not have any fields of study. [ex: UNITID 114415].

Bugfix: Institutions without any Fields of Study

---

js/src/components/vue/NameAutocomplete.vue

This update allows more than one school to be shown when selecting an item from the autocomplete drop-down menu on the name search if there is more than one institution with the same name.

Bugfix: Duplicate Institution Names
